name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libcurl4-gnutls-dev
      - name: Set up ${{ matrix.compiler }}
        run: |
          if [ "${{ matrix.compiler }}" == "clang" ]; then
            sudo apt-get install -y clang;
          fi
      - name: Install clib
        run: |
          git clone https://github.com/clibs/clib.git
          cd clib
          make
          sudo make install
      - name: Run tests
        run: make CC=${{ matrix.compiler }} CFLAGS="-std=gnu11" LDFLAGS="-lm" install test

  test-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: brew install curl
      - name: Install ${{ matrix.compiler }}
        run: |
          if [ "${{ matrix.compiler }}" == "gcc" ]; then
            brew install gcc;
          fi
      - name: Install clib
        run: |
          git clone https://github.com/clibs/clib.git
          cd clib
          make CC=${{ matrix.compiler }}
          sudo make install
      - name: Run tests with ${{ matrix.compiler }}
        run: make CC=${{ matrix.compiler }} CFLAGS="-std=c11" install test

  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Install dependencies
        run: |
          choco install make
          choco install curl
      - name: Download clib deps
        run: |
          mkdir -p deps\greatest
          curl -L https://github.com/silentbicycle/greatest/raw/release/greatest.h -o deps\greatest\greatest.h
          mkdir -p deps\aligned
          curl -L https://raw.githubusercontent.com/goodcleanfun/aligned/refs/heads/main/src/aligned.h -o deps\aligned\aligned.h
          mkdir -p deps\simde_avx2
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/avx.h -o deps\simde_avx2\avx.h
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/avx2.h -o deps\simde_avx2\avx2.h
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/check.h -o deps\simde_avx2\check.h
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/debug-trap.h -o deps\simde_avx2\debug-trap.h
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/hedley.h -o deps\simde_avx2\hedley.h
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/mmx.h -o deps\simde_avx2\mmx.h
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/simde-align.h -o deps\simde_avx2\simde-align.h
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/simde-arch.h -o deps\simde_avx2\simde-arch.h
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/simde-common.h -o deps\simde_avx2\simde-common.h
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/simde-constify.h -o deps\simde_avx2\simde-constify.h
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/simde-detect-clang.h -o deps\simde_avx2\simde-detect-clang.h
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/simde-diagnostic.h -o deps\simde_avx2\simde-diagnostic.h
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/simde-f16.h -o deps\simde_avx2\simde-f16.h
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/simde-features.h -o deps\simde_avx2\simde-features.h
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/simde-math.h -o deps\simde_avx2\simde-math.h
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/sse.h -o deps\simde_avx2\sse.h
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/sse2.h -o deps\simde_avx2\sse2.h
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/sse3.h -o deps\simde_avx2\sse3.h
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/sse4.1.h -o deps\simde_avx2\sse4.1.h
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/sse4.2.h -o deps\simde_avx2\sse4.2.h
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/ssse3.h -o deps\simde_avx2\ssse3.h

      - name: Run tests with MSVC
        run: make CC=cl CFLAGS="/std:c11" test

  test-windows-mingw:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Verify GCC Version
        run: |
          gcc --version
      - name: Install curl
        run: |
          choco install curl -y
      - name: Download clib deps
        run: |
          mkdir -p deps/greatest
          curl -L https://github.com/silentbicycle/greatest/raw/release/greatest.h -o deps/greatest/greatest.h
          mkdir -p deps/aligned
          curl -L https://raw.githubusercontent.com/goodcleanfun/aligned/refs/heads/main/src/aligned.h -o deps/aligned/aligned.h
          mkdir -p deps/simde_avx2
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/avx.h -o deps/simde_avx2/avx.h
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/avx2.h -o deps/simde_avx2/avx2.h
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/check.h -o deps/simde_avx2/check.h
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/debug-trap.h -o deps/simde_avx2/debug-trap.h
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/hedley.h -o deps/simde_avx2/hedley.h
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/mmx.h -o deps/simde_avx2/mmx.h
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/simde-align.h -o deps/simde_avx2/simde-align.h
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/simde-arch.h -o deps/simde_avx2/simde-arch.h
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/simde-common.h -o deps/simde_avx2/simde-common.h
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/simde-constify.h -o deps/simde_avx2/simde-constify.h
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/simde-detect-clang.h -o deps/simde_avx2/simde-detect-clang.h
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/simde-diagnostic.h -o deps/simde_avx2/simde-diagnostic.h
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/simde-f16.h -o deps/simde_avx2/simde-f16.h
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/simde-features.h -o deps/simde_avx2/simde-features.h
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/simde-math.h -o deps/simde_avx2/simde-math.h
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/sse.h -o deps/simde_avx2/sse.h
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/sse2.h -o deps/simde_avx2/sse2.h
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/sse3.h -o deps/simde_avx2/sse3.h
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/sse4.1.h -o deps/simde_avx2/sse4.1.h
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/sse4.2.h -o deps/simde_avx2/sse4.2.h
          curl -L https://raw.githubusercontent.com/goodcleanfun/simde_avx2/refs/heads/main/src/ssse3.h -o deps/simde_avx2/ssse3.h

      - name: Build and Test with MinGW
        run: |
          make CC=gcc CFLAGS="-std=c11" test